### PR TITLE
New pull request

### PR DESCRIPTION
**Pull request by LornaLynch**
I have  (I think) fixed the code, and there are various other copy edits. I've altered instances of PiCamera when this refers to the actual camera module, rather than the code.

### CODE REVIEW

**Comment by bennuttall** [comment]
You're right to correct "the PiCamera" to "the camera" in the wording in the worksheet.

In the code:

``` python
from picamera import PiCamera
```

Here `picamera` is the name of the module, and you're importing the `PiCamera` class from the module. Module names are usually (should be) lower case (sometimes contains capitals due to acronyms but probably shouldn't). Class names should be (what some call) `TitleCase`.

You will see other examples like:

``` python
from time import sleep
```

Here `time` is the module, and `sleep` is a function, both of which are (and should be) lower case.

When I say "should be" I'm referring to the author of the module - but if they are actually named in a different style, that's what we have to do because that's how it's named!

You might want to have a read of the Python Style Guide I've been writing - it's still WIP: https://github.com/raspberrypilearning/python-style-guide

**Comment by bennuttall** [comment]
I just realised this resource refers to the new Guides repository, but this resource will be released before Guides will. Could you copy the camera setup step from one of the others, like Push Button Stop Motion?

**Comment by LornaLynch** [comment]
Will do.

Lorna Lynch
Raspberry Pi Foundation
www.raspberrypi.orghttp://www.raspberrypi.org

On 28 May 2015, at 15:19, Ben Nuttall <notifications@github.com<mailto:notifications@github.com>> wrote:

I just realised this resource refers to the new Guides repository, but this resource will be released before Guides will. Could you copy the camera setup step from one of the others, like Push Button Stop Motion?

##

**Comment by LornaLynch** [comment]
Thanks, that'd be really helpful. I'm not really au fait with style in Python.

Lorna Lynch
Raspberry Pi Foundation
www.raspberrypi.orghttp://www.raspberrypi.org

On 28 May 2015, at 15:14, Ben Nuttall <notifications@github.com<mailto:notifications@github.com>> wrote:

You're right to correct "the PiCamera" to "the camera" in the wording in the worksheet.

In the code:

from picamera import PiCamera

Here picamera is the name of the module, and you're importing the PiCamera class from the module. Module names are usually (should be) lower case (sometimes contains capitals due to acronyms but probably shouldn't). Class names should be (what some call) TitleCase.

You will see other examples like:

from time import sleep

Here time is the module, and sleep is a function, both of which are (and should be) lower case.

When I say "should be" I'm referring to the author of the module - but if they are actually named in a different style, that's what we have to do because that's how it's named!

You might want to have a read of the Python Style Guide I've been writing - it's still WIP: https://github.com/raspberrypilearning/python-style-guide

##

**Pull request closed without merging**
