### PR TITLE
Copy edit on resource

### PR DESCRIPTION
**Pull request by LornaLynch**
Still trying to merge the copy edits, and the code fix... 
@bennuttall - my profile in the desktop client should be corrected now.

### CODE REVIEW

**Comment by bennuttall** [comment]
Is this still needed or have edits been covered elsewhere?

**Comment by LornaLynch** [comment]
It's still needed, please.

Lorna Lynch
Raspberry Pi Foundation
www.raspberrypi.orghttp://www.raspberrypi.org

On 28 May 2015, at 15:22, Ben Nuttall <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this still needed or have edits been covered elsewhere?

##

**Comment by LornaLynch** [comment]
@bennuttall This pull request is still needed, but can I still make changes to the master document in the Raspberry Pi Learning repo, or will that cause further issues with merging this pull request? 
I wanted to alter the references to Guides in the text, as requested in #7

**Comment by LornaLynch** [comment]
ETA - I've added the camera setup instructions to the worksheet. I don't know if this might have really messed up this PR, but, if so, could you let me know? It does still need to be merged if possible.

**Comment by LornaLynch** [comment]
Don't worry about it: the two versions have probably now diverged so far that merging won't be possible. I'm making changes by hand.

**Pull request closed without merging**
