### PR TITLE
Copy edit on resource

### PR DESCRIPTION
**Pull request by LornaLynch**
I've copy edited this in the desktop client, but GitHub won't let me merge it to the master myself. Could you give me a hand?

### CODE REVIEW

**Comment by bennuttall** [comment]
Is this PR not needed any more?

**Comment by bennuttall** [comment]
You made a change in this PR:

`from picamera import PiCamera` to `from picamera import picamera`

but you didn't seem to make the change in the other PR that went through, which is good because this change would have broken the code.

**Comment by LornaLynch** [comment]
Ack: sorry. I though it was correct: I wasn't sure about the capitalisation so I did some checking and assumed it should be all lower case. Never assume! I still have my copy of the repo in the desktop client, so I can correct the code tomorrow. 

I can close this pull request and start a new one: I've made quite a few spelling/punctuation/grammar-type changes, so I'd still like to merge that version.

**Comment by LornaLynch** [comment]
I'm going to close this pull request and open a new one with the code corrected.

**Pull request closed without merging**
